print("=+=+=+=+ Data Diri Mahasiswa +=+=+=+=")
nim = input("Nim :")
nama = input("Nama :")
jurusan = input("Jurusan :")
alamat = input("Alamat :")

print("Hasil Cetak data diatas")
print("NIM      :", str(nim))
print("Nama     :", str(nama))
print("Jurusan  :", str(jurusan))
print("Alamat   :", str(alamat))