print("{:^40}".format("TOKO MAINAN ANAK"))
print("============================================")
nama = str(input("Masukan Nama Pembeli : "))
kode = str(input("Masukan Kode Mainan  : "))
harga = int(input("Masukan Harga Barang : Rp."))
jumlahbeli = int(input("Masukan Jumlah Beli  : "))
print("============================================")
print("Nama Pembeli\t=", nama)
print("Kode Mainan\t=", kode)
print("Harga Barang\t= Rp.", harga, sep='')
print("Jumlah Beli\t=", jumlahbeli, "Buah")
total = jumlahbeli*harga
print("Total Belanja\t= Rp.", total, sep='')
print("============================================")