print("{:^40}".format("Penghitung Kembalian Ibu"))
print("="*40)
brt = int(input("Masukan Berat Telur/Kg : "))
hrg = int(input("Masukan Harga Telur    : Rp."))
ongkos = int(input("Masukan Ongkos PP      : Rp."))
uang = int(input("Masukan Uang Ibu       : Rp."))
sisa = (uang-ongkos)
sisa = sisa%(brt*hrg)
print("="*40)
print("Sisa Uang Ibu Adalah   : Rp.",sisa, sep='')
print("="*40)